site_name: AD - Accés a Dades

extra_css:
  - css/extra.css

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc

nav:

#- UD 4. BD NoSQL:
#  - 1 - Les Bases de Dades Orientades a Objectes: 3__bases_de_dades_orientades_a_objectes.md
#  - 2 - Exercicis: exercicis.md


- UD 5. BD NoSQL:
  - 1 - Introducció: 1__introducci.md
  - 2 - Bases de Dades Clau-Valor: 2__bases_de_dades_clauvalor.md
   #- 2.1 - Instal·lació de Redis: 21__installaci_de_redis.md
   #- 2.2 - Utilització de Redis: 22__utilitzaci_de_redis.md
   #  - 2.2.1 - Strings: 221__strings.md
   #  - 2.2.2 - Keys: 222__keys.md
   #  - 2.2.3 - Hash: 223__hash.md
   #  - 2.2.4 - List: 224__list.md
   #  - 2.2.5 - Set: 225__set.md
   #  - 2.2.6 - Set ordenat: 226__set_ordenat.md
   #- 2.3 - Connexió des de Kotlin: 23__connexi_des_de_kotlin.md
  - 3 - MongoDB: 3__mongodb.md
   #- 3.1 - Instal·lació de MongoDB: 31__installaci_de_mongodb.md
   #  - 3.1.1 - Connexió al servidor de l'Institut: 311__connexi_al_servidor_de_linstitut.md
   #- 3.2 - Utilització de MongoDB: 32__utilitzaci_de_mongodb.md
   #  - 3.2.1 - Tipus de dades: 321__tipus_de_dades.md
   #  - 3.2.2 - Operacions bàsiques: 322__operacions_bsiques.md
   #  - 3.2.3 - Operacions d'actualització avançada: 323__operacions_dactualitzaci_avanada.md
   #    - 3.2.3.1 - $set: 3231__set.md
   #    - 3.2.3.2 - $unset: 3232__unset.md
   #    - 3.2.3.3 - $rename: 3233__rename.md
   #    - 3.2.3.4 - $inc: 3234__inc.md
   #    - 3.2.3.5 - Elements d'un array: 3235__elements_dun_array.md
   #    - 3.2.3.6 - Inserció en Arrays: $push: 3236__inserci_en_arrays_push.md
   #    - 3.2.3.7 - Eliminació en arrays: $pop i $pull: 3237__eliminaci_en_arrays_pop_i_pull.md
   #    - 3.2.3.8 - Upsert: 3238__upsert.md
   #- 3.3 - Consulta de documents: 33__consulta_de_documents.md
   #  - 3.3.1 - Paràmetres de les funcions find() i findOne(): 331__parmetres_de_les_funcions_find_i_findone.md
   #  - 3.3.2 - Operadors de les condicions: 332__operadors_de_les_condicions.md
   #  - 3.3.3 - Agregació: 333__agregaci.md
   #- 3.4 - Connexió des de Kotlin: 34__connexi_des_de_kotlin.md
   #- 3.5 - Connexió des de Kotlin al servidor de l'Institut: 35__connexi_des_de_kotlin_al_servidor_de_linstitut.md
  - Exercicis: exercicis.md