site_name: AD - Accés a Dades

extra_css:
  - css/extra.css
  - img/favicon.ico 

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences 
  - tables    
  - attr_list
  - toc

nav:

#- UD 4. BD NoSQL:
#  - 1 - Les Bases de Dades Orientades a Objectes: 3__bases_de_dades_orientades_a_objectes.md
#  - 2 - Exercicis: exercicis.md


- UD 5. BD NoSQL:
  - 1 - Introducció: 1__introducci.md
  - 2 - Bases de Dades Clau-Valor: 2__bases_de_dades_clauvalor.md
  - 3 - MongoDB: 3__mongodb.md
  - Exercicis: exercicis.md